export const BUSINESSES_SEARCH_PENDING = `BUSINESSES_SEARCH_PENDING`;

export const BUSINESSES_SEARCH_FULLFILLED = "BUSINESSES_SEARCH_FULLFILLED";

export const BUSINESSES_SEARCH_REJECTED = "BUSINESSES_SEARCH_REJECTED";

export const RESET_BUSINESSES_SEARCH = "RESET_BUSINESSES_SEARCH";