export const BUSINESSES_DETAIL_PENDING = `BUSINESSES_DETAIL_PENDING`;

export const BUSINESSES_DETAIL_FULLFILLED = "BUSINESSES_DETAIL_FULLFILLED";

export const BUSINESSES_DETAIL_REJECTED = "BUSINESSES_DETAIL_REJECTED";

export const RESET_BUSINESSES_DETAIL = "RESET_BUSINESSES_DETAIL";